"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import SessionWrapper from "@/components/auth/SessionWrapper";
import "./scss/globals.scss";

//New
import { useTheme } from '@/hooks/useTheme';
import DarkLight from "@/components/layout/DarkLight";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { lightMode, toggleMode, mounted } = useTheme();

  // No renderizar el DarkLight hasta que esté montado para evitar hidratación
  if (!mounted) {
    return (
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={lightMode ? 'light-mode' : ''}>
        <DarkLight lightMode={lightMode} toggleMode={toggleMode} />
        {children}
      </body>
    </html>
  );
}


//Old
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "FinancialSage",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler.min.css" rel="stylesheet"/>
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <SessionWrapper>
//           {children}
//         </SessionWrapper>
//       </body>
//     </html>
//   );
// }
